---
- name: Install EPEL Repo
  hosts: all
  become: true
  
  tasks:
     - name: Install nginx
         yum:
           name: nginx
           state: latest
#    - name: Выполнение двух действий
#      become: true
#      shell:
#        cmd: |
#          sudo -i
#          yum install epel-release -y
#          yum install -y nginx